// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: demo.proto

package hipstershop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	DiscountCodeService_ApplyDiscount_FullMethodName = "/hipstershop.DiscountCodeService/ApplyDiscount"
)

// DiscountCodeServiceClient is the client API for DiscountCodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscountCodeServiceClient interface {
	ApplyDiscount(ctx context.Context, in *ApplyDiscountRequest, opts ...grpc.CallOption) (*ApplyDiscountResponse, error)
}

type discountCodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscountCodeServiceClient(cc grpc.ClientConnInterface) DiscountCodeServiceClient {
	return &discountCodeServiceClient{cc}
}

func (c *discountCodeServiceClient) ApplyDiscount(ctx context.Context, in *ApplyDiscountRequest, opts ...grpc.CallOption) (*ApplyDiscountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyDiscountResponse)
	err := c.cc.Invoke(ctx, DiscountCodeService_ApplyDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscountCodeServiceServer is the server API for DiscountCodeService service.
// All implementations must embed UnimplementedDiscountCodeServiceServer
// for forward compatibility.
type DiscountCodeServiceServer interface {
	ApplyDiscount(context.Context, *ApplyDiscountRequest) (*ApplyDiscountResponse, error)
	mustEmbedUnimplementedDiscountCodeServiceServer()
}

// UnimplementedDiscountCodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscountCodeServiceServer struct{}

func (UnimplementedDiscountCodeServiceServer) ApplyDiscount(context.Context, *ApplyDiscountRequest) (*ApplyDiscountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyDiscount not implemented")
}
func (UnimplementedDiscountCodeServiceServer) mustEmbedUnimplementedDiscountCodeServiceServer() {}
func (UnimplementedDiscountCodeServiceServer) testEmbeddedByValue()                            {}

// UnsafeDiscountCodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscountCodeServiceServer will
// result in compilation errors.
type UnsafeDiscountCodeServiceServer interface {
	mustEmbedUnimplementedDiscountCodeServiceServer()
}

func RegisterDiscountCodeServiceServer(s grpc.ServiceRegistrar, srv DiscountCodeServiceServer) {
	// If the following call panics, it indicates UnimplementedDiscountCodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscountCodeService_ServiceDesc, srv)
}

func _DiscountCodeService_ApplyDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountCodeServiceServer).ApplyDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscountCodeService_ApplyDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountCodeServiceServer).ApplyDiscount(ctx, req.(*ApplyDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscountCodeService_ServiceDesc is the grpc.ServiceDesc for DiscountCodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscountCodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.DiscountCodeService",
	HandlerType: (*DiscountCodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyDiscount",
			Handler:    _DiscountCodeService_ApplyDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}